/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HealthSeekerRecord = IDL.Record({
  'bp' : IDL.Text,
  'id' : IDL.Nat,
  'age' : IDL.Text,
  'weight' : IDL.Text,
  'height' : IDL.Text,
  'movementScore' : IDL.Nat,
  'sleepScore' : IDL.Nat,
  'mindScore' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'profession' : IDL.Text,
  'whatsapp' : IDL.Text,
  'submittedAt' : IDL.Int,
  'thyroid' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'gutScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'sugar' : IDL.Text,
  'gender' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getSubmissionById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(HealthSeekerRecord)],
      ['query'],
    ),
  'getSubmissions' : IDL.Func([], [IDL.Vec(HealthSeekerRecord)], ['query']),
  'submitAssessment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HealthSeekerRecord = IDL.Record({
    'bp' : IDL.Text,
    'id' : IDL.Nat,
    'age' : IDL.Text,
    'weight' : IDL.Text,
    'height' : IDL.Text,
    'movementScore' : IDL.Nat,
    'sleepScore' : IDL.Nat,
    'mindScore' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'profession' : IDL.Text,
    'whatsapp' : IDL.Text,
    'submittedAt' : IDL.Int,
    'thyroid' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'gutScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'sugar' : IDL.Text,
    'gender' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getSubmissionById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(HealthSeekerRecord)],
        ['query'],
      ),
    'getSubmissions' : IDL.Func([], [IDL.Vec(HealthSeekerRecord)], ['query']),
    'submitAssessment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };