/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HealthSeekerRecord {
  'bp' : string,
  'id' : bigint,
  'age' : string,
  'weight' : string,
  'height' : string,
  'movementScore' : bigint,
  'sleepScore' : bigint,
  'mindScore' : bigint,
  'answers' : Array<bigint>,
  'name' : string,
  'profession' : string,
  'whatsapp' : string,
  'submittedAt' : bigint,
  'thyroid' : string,
  'email' : [] | [string],
  'gutScore' : bigint,
  'totalScore' : bigint,
  'sugar' : string,
  'gender' : string,
  'category' : string,
}
export interface _SERVICE {
  'getSubmissionById' : ActorMethod<[bigint], [] | [HealthSeekerRecord]>,
  'getSubmissions' : ActorMethod<[], Array<HealthSeekerRecord>>,
  'submitAssessment' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      Array<bigint>,
    ],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];