/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HealthSeekerRecord {
    bp: string;
    id: bigint;
    age: string;
    weight: string;
    height: string;
    movementScore: bigint;
    sleepScore: bigint;
    mindScore: bigint;
    answers: Array<bigint>;
    name: string;
    profession: string;
    whatsapp: string;
    submittedAt: bigint;
    thyroid: string;
    email?: string;
    gutScore: bigint;
    totalScore: bigint;
    sugar: string;
    gender: string;
    category: string;
}
export interface backendInterface {
    deleteSubmission(id: bigint): Promise<boolean>;
    getSubmissionById(id: bigint): Promise<HealthSeekerRecord | null>;
    getSubmissions(): Promise<Array<HealthSeekerRecord>>;
    submitAssessment(name: string, gender: string, age: string, profession: string, weight: string, height: string, bp: string, sugar: string, thyroid: string, whatsapp: string, email: string | null, answers: Array<bigint>): Promise<bigint>;
}
import type { HealthSeekerRecord as _HealthSeekerRecord } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async deleteSubmission(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async getSubmissionById(arg0: bigint): Promise<HealthSeekerRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubmissions(): Promise<Array<HealthSeekerRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissions();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissions();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAssessment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string | null, arg11: Array<bigint>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAssessment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg10), arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAssessment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n6(this._uploadFile, this._downloadFile, arg10), arg11);
            return result;
        }
    }
}
function from_candid_HealthSeekerRecord_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthSeekerRecord): HealthSeekerRecord {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthSeekerRecord]): HealthSeekerRecord | null {
    return value.length === 0 ? null : from_candid_HealthSeekerRecord_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bp: string;
    id: bigint;
    age: string;
    weight: string;
    height: string;
    movementScore: bigint;
    sleepScore: bigint;
    mindScore: bigint;
    answers: Array<bigint>;
    name: string;
    profession: string;
    whatsapp: string;
    submittedAt: bigint;
    thyroid: string;
    email: [] | [string];
    gutScore: bigint;
    totalScore: bigint;
    sugar: string;
    gender: string;
    category: string;
}): {
    bp: string;
    id: bigint;
    age: string;
    weight: string;
    height: string;
    movementScore: bigint;
    sleepScore: bigint;
    mindScore: bigint;
    answers: Array<bigint>;
    name: string;
    profession: string;
    whatsapp: string;
    submittedAt: bigint;
    thyroid: string;
    email?: string;
    gutScore: bigint;
    totalScore: bigint;
    sugar: string;
    gender: string;
    category: string;
} {
    return {
        bp: value.bp,
        id: value.id,
        age: value.age,
        weight: value.weight,
        height: value.height,
        movementScore: value.movementScore,
        sleepScore: value.sleepScore,
        mindScore: value.mindScore,
        answers: value.answers,
        name: value.name,
        profession: value.profession,
        whatsapp: value.whatsapp,
        submittedAt: value.submittedAt,
        thyroid: value.thyroid,
        email: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.email)),
        gutScore: value.gutScore,
        totalScore: value.totalScore,
        sugar: value.sugar,
        gender: value.gender,
        category: value.category
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthSeekerRecord>): Array<HealthSeekerRecord> {
    return value.map((x)=>from_candid_HealthSeekerRecord_n2(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
